---
deployment:
  tasks:
    - export DEPLOYPATH=/home/n1579226/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R mazer $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
